[build]
  publish = "public"  # Your public directory where the build output is placed
  command = "npm run build"  
  [[headers]]
    for = "/styles/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
